// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaFolha.Models;

namespace ProvaFolha.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221004152437_novoBd")]
    partial class novoBd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProvaFolha.Models.Folha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncinarioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Impostinss")
                        .HasColumnType("REAL");

                    b.Property<double>("Impostofgts")
                        .HasColumnType("REAL");

                    b.Property<double>("Impostorenda")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantidadedehoras")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SalarioLiquido")
                        .HasColumnType("REAL");

                    b.Property<double>("Salariobruto")
                        .HasColumnType("REAL");

                    b.Property<double>("Valorhora")
                        .HasColumnType("REAL");

                    b.Property<int>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FuncinarioId");

                    b.ToTable("Folhas");
                });

            modelBuilder.Entity("ProvaFolha.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Salario")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ProvaFolha.Models.Folha", b =>
                {
                    b.HasOne("ProvaFolha.Models.Funcionario", "Funcinario")
                        .WithMany()
                        .HasForeignKey("FuncinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcinario");
                });
#pragma warning restore 612, 618
        }
    }
}
